---
name: Benjamin
surname: Elsner
address: "University College Dublin, School of Economics, Belfield, Dublin 4, Ireland"
phone: +353 1 716 8446
www: benjaminelsner.com
email: "benjamin.elsner@ucd.ie"
twitter: ben_elsner
github: benelsner82
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
docname: Anschreiben
header-includes:
  - \usepackage{setspace}
  - \setlength{\parindent}{0pt}
  - \usepackage{parskip}
  - \setlength{\parskip}{1.5ex plus 0.5ex minus 0.2ex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(vitae)
library(dplyr)
library(scholar)

scholarben <- get_profile("jvyIv10AAAAJ")

#scholarben <- as.data.frame(1)
#scholarben$total_cites <- 1
#scholarben$h_index <- 1
```


Sehr geehrte Damen und Herren, 


Hiermit möchte ich mich auf die ausgeschriebene W3-Professur Internationale Wirtschaft an der TU Dortmund bewerben. Ich bin derzeit Assistant Professor mit Tenure am University College Dublin, der größten und forschungsstärksten Fakultät Irlands. Meine Forschungs- und Lehrinteressen passen ausgezeichnet zum Profil der ausgeschriebenen Professur. Zudem ist die VWL-Fakultät an der TU dank der Berufungen der letzten Jahre stark im Aufwind, was die Position -- und eine damit verbundene Rückkehr nach Deutschland -- sehr interessant für mich machen würde.  


Meine Forschung liegt an der Schnittstelle zwischen internationaler Ökonomie, Arbeitsmarkt- und Umweltökonomie. Der Großteil meiner Forschungsarbeiten behandelt die Frage, wie sich internationale Migration auf die Herkunfts- und Zielländer auswirkt. Dies ist zweifelsohne ein sehr wichtiges Thema in der internationalen Wirtschaft, da in naher Zukunft durch den Klimawandel und Konflikte deutlich stärkere Migrationsbewegungen zu erwarten sind. Meine gegenwärtigen Forschung widmet sich der Frage, ob und wie Zuwanderung die Steuer- und Ausgabenpolitik auf lokaler Ebene verändert. In vielen Ländern tragen Städte und Gemeinden die Hauptlast der Unterbringung und Integration von Zuwanderern, vor allem Flüchtlingen. Es ist daher wichtig zu verstehen, welche wirtschaftlichen Konsequenzen Migration in den Kommunen hat, und welche wirtschaftspolitischen Instrumente genutzt werden können, um die Folgen von Zuwanderung abzufedern. Das erste Forschungspapier zu diesem Thema ist gerade "conditionally accepted" beim Journal of the European Economic Association; weitere Papiere zu diesem Thema sind derzeit in Arbeit. 


Für meine Forschung verwende ich sowohl empirische als auch theoretische Methoden. Die meisten meiner in letzter Zeit veröffentlichten Papiere beruhen auf kausaler Identifikation; allerdings verwende ich in einigen meiner Papiere strukturelle Methoden (quantitative Theorie) um z.B. globale Wohlfahrtseffekte von Migration abzuschätzen. Beispiele hierfür sind meine 2020 im Journal of Development Economics und mein 2014 im Journal of International Economics publizierte Papiere. Neben den erwähnten Journals sind meine Arbeiten in hochrangigen Journals wie Economic Journal, Journal of Labor Economics, Journal of Human Resources, oder Journal of Environmental Economics and Management erschienen. Meine Forschungsarbeit wurde unter anderem mit Drittmitteln des Irish Research Council, der Weltbank und des Bundesministeriums für Bildung und Forschung finanziert. 


In der Lehre liegen meine Schwerpunkte auf Ökonometrie, Economics of Globalization, und Finanzwissenschaft. Ein Kurs welcher besonders gut zu der ausgeschriebenen Professur passen würde ist Economics of Migration, welchen ich bereits an der Universität Luxemburg, der Universität Regensburg und seit diesem Jahr am University College Dublin unterrichtet habe. Zudem könnte ich mir sehr gut vorstellen, einen Kurs Economics of Globalization zu entwerfen, welcher Aussenhandel, FDI und Migration theoretisch und empirisch beleuchtet. Neben der Forschung ist mir die Lehre sehr wichtig, vor allem die Weiterentwicklung von Materialien und die Nutzung neuer Technologien. Seit 2021 habe ich einen YouTube Kanal mit über 70 Lehrvideos, über 2000 Abonnenten und über 50,000 clicks pro Jahr. Zudem habe ich am UCD einen neuen Masterstudiengang  MSc Economics and Data Analytics aufgebaut. Für meine Verdienste in der Lehre wurde ich vom University College Dublin mit dem alle zwei Jahre verliehenen Teaching and Learning Award ausgezeichnet. 


Durch meine Arbeit am IZA in Bonn (2012-2017) und vor allem meine Rolle als Deputy Director des Bereichs Mobility and Migration (2014-2020) habe ich ein sehr großes Forschungsnetzwerk aufgebaut, von welchem die TU Dortmund sicherlich profitieren könnte. Zudem habe ich in Dublin Forschungskooperationen mit Eurofound (EU Forschungszentrum), dem Central Statistics Office und LinkedIn aufgebaut; mit diesen forsche ich derzeit zum Thema Migration sowie zu den Auswirkungen des Brexit. 


Besonders am Herzen liegt mir die Förderung des wissenschaftlichen Nachwuchs. Seit 2018 habe ich in Dublin das MLitt/PhD Programm in Economics aufgebaut, das einzige strukturierte PhD Programm in Irland. Die größten Neuerungen des Programms waren ein einjähriges Kursprogramm auf PhD Niveau, strukturierte Vorbereitung auf den Arbeitsmarkt, und vor allem ein deutlicher Anstieg in der Anzahl der Doktoranden: von 15 im Jahr 2017 auf über 50 im Jahr 2021. Ich selbst betreute und betreue acht Dissertationen. Drei meiner Doktoranden haben ihre Promotion bereits beendet und ausgezeichnete Placements erzielt: Diego Zambiasi ist Lecturer mit Tenure an der Newcastle University, Emanuele Albarosa ist Ökonom bei der International Organization for Migration (IOM, Vereinte Nationen) und Stefano Ceolotto ist Post-Doc am Institut ESRI in Dublin. 


Ich bin überzeugt, dass ich mit meiner Forschung und Lehre, sowie meiner Managementerfahrung vom IZA und UCD deutlich zum Erfolg der TU Dortmund beitragen werde. Gleichzeitig hat meine Forschung große Schnittmengen mit Professoren an der TU, vor allem Michael Böhm (Arbeitsmärkte), Lukas Buchheim (politische Ökonomie und Arbeitsmärkte), Christiane Hellmanzik (internationale Ökonomie) und Matthias Westphal (Arbeitsmärkte). Sowohl beruflich als auch privat wäre ich sehr interessiert daran, nach Deutschland zurückzukehren, und die TU Dortmund wäre hierfür eine ausgezeichnete Adresse. 


Im Anhang sende ich meinen Lebenslauf, Kopien meiner Zeugnisse (PhD und Diplom) sowie ein Forschungs- und Lehrkonzept. Ich würde mich sehr über eine Einladung zum Berufungsvortrag freuen. Für Fragen stehe ich jederzeit per Email oder telefonisch (+353 896116112) zur Verfügung.
